### ISSUE TITLE
A proper name

### ISSUE THREAD

**Issue by ChaoticLaw** [hipdesignchat/event-planner#9]
We don't have a proper name for this product, so we should get one at some point. While low priority, we've had a couple of suggestions:

  - Event
  - Ventee
 
Discuss the merits, which ones you like, and if you have any suggestions, feel free to add them.

**Comment by PatrickE-626** [comment]
I might have a few suggestions, but they may not be great:

- Acara (Malay translation for Event)
- Jev (Czech translation for Phenomenon)
- Quod (Latin translation for Belonging)
- Reiseziel (German translation for Destination)

**Comment by ChaoticLaw** [comment]
How about something like 'Quodivent'? It's a sort of mishmash between the Latin translation and 'event', which is the subject of our application.

**Comment by jamespsp** [comment]
Quodivent sounds like a high-end database company, or some syndicate in a post-dystopic world

**Comment by ChaoticLaw** [comment]
We'll make it our project's code name, and we can leave the name as event planner.
